### ISSUE TITLE
Null Pointer

### ISSUE THREAD

**Issue by AdmirilRed** [AdmirilRed/WatchGuard-XML-Reporter#1]
Exception in thread “main” java.lang.NullPointerException
                at reporting.reportGenerator.extract(ReportGenerator.java:142)
                at reporting.reportGenerator.traverse(ReportGenerator.java:92)
                at reporting.reportGenerator.traverse(ReportGenerator.java:90)
                at reporting.reportGenerator.main(ReportGenerator.java:45)

I tried it on a smaller folder that I had copied to my desktop with 10 subfolders, it generated an empty report. Then I tried it at \\corwgvrv\video.storage where it gave me the above error. Then I tried mapping the drive to see if it was because of the network address and also got the above error again.

**Comment by AdmirilRed** [comment]
If I give it the path, including a folder that has the .xml file it works, but only for that one xml file. We need to give it the folder that is one level up from that and have it parse the folder names and use them to get the xml files.

**Comment by AdmirilRed** [comment]
Fixed in commit 94adf51
